[package]
name = "rsvg-convert"
version = "0.3.1"
authors = ["Michael"]
edition = "2018"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.3", features = ["std", "derive", "help"], default-features = false }
