[package]
name = "rsvg-convert"
version = "0.3.0"
authors = ["Michael"]
edition = "2018"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.13", features = ["std", "derive", "help"], default-features = false }
